// Independent cross-check of docs/receipt-v1-vectors.json using @mysten/sui's bcs
// implementation (the vectors were generated by a hand-rolled Python BCS writer).
import { bcs } from '@mysten/sui/bcs'
import { readFileSync } from 'node:fs'

const ReceiptV1 = bcs.struct('ReceiptV1', {
  receipt_id: bcs.vector(bcs.u8()),
  config_hash: bcs.vector(bcs.u8()),
  request_hash: bcs.vector(bcs.u8()),
  upstream_request_hash: bcs.vector(bcs.u8()),
  model_id: bcs.string(),
  response_hash: bcs.vector(bcs.u8()),
  input_tokens: bcs.u64(),
  output_tokens: bcs.u64(),
  outcome: bcs.u8(),
})

const IntentMessage = bcs.struct('IntentMessage', {
  intent: bcs.u8(),
  timestamp_ms: bcs.u64(),
  payload: ReceiptV1,
})

const hexToBytes = (h: string) => Uint8Array.from(h.match(/.{2}/g)!.map((b) => parseInt(b, 16)))
const toHex = (b: Uint8Array) => Array.from(b).map((x) => x.toString(16).padStart(2, '0')).join('')

const doc = JSON.parse(
  readFileSync(new URL('../docs/receipt-v1-vectors.json', import.meta.url), 'utf8'),
)

let failures = 0
for (const v of doc.vectors) {
  const f = v.fields
  const bytes = IntentMessage.serialize({
    intent: f.intent,
    timestamp_ms: BigInt(f.timestamp_ms),
    payload: {
      receipt_id: hexToBytes(f.receipt_id),
      config_hash: hexToBytes(f.config_hash),
      request_hash: hexToBytes(f.request_hash),
      upstream_request_hash: hexToBytes(f.upstream_request_hash),
      model_id: f.model_id,
      response_hash: hexToBytes(f.response_hash),
      input_tokens: BigInt(f.input_tokens),
      output_tokens: BigInt(f.output_tokens),
      outcome: f.outcome,
    },
  }).toBytes()

  const got = toHex(bytes)
  const lenOk = bytes.length === v.byte_length
  const hexOk = got === v.expected_bcs_hex
  if (!lenOk || !hexOk) {
    failures++
    console.log(`FAIL ${v.name}: len ${bytes.length} (expected ${v.byte_length})`)
    console.log(`  got      ${got}`)
    console.log(`  expected ${v.expected_bcs_hex}`)
  } else {
    console.log(`PASS ${v.name}: ${bytes.length} bytes match`)
  }
}
console.log(failures === 0 ? 'ALL VECTORS VERIFIED' : `${failures} VECTOR(S) FAILED`)
process.exit(failures === 0 ? 0 : 1)
