// Independent cross-check of docs/receipt-vectors.json using @mysten/sui's bcs
// implementation (the vectors were generated by a hand-rolled Python BCS writer).
import { bcs } from '@mysten/sui/bcs'
import { readFileSync } from 'node:fs'

const Receipt = bcs.struct('Receipt', {
  receipt_id: bcs.vector(bcs.u8()),
  config_hash: bcs.vector(bcs.u8()),
  provider: bcs.u8(),
  endpoint_host: bcs.string(),
  tls_cert_sha256: bcs.vector(bcs.u8()),
  request_blob: bcs.u256(),
  upstream_request_blob: bcs.u256(),
  upstream_headers_hash: bcs.vector(bcs.u8()),
  model_id: bcs.string(),
  provider_request_id: bcs.string(),
  response_blob: bcs.u256(),
  provider_meta_hash: bcs.vector(bcs.u8()),
  input_tokens: bcs.u64(),
  cache_creation_tokens: bcs.u64(),
  cache_read_tokens: bcs.u64(),
  output_tokens: bcs.u64(),
  outcome: bcs.u8(),
})

const IntentMessage = bcs.struct('IntentMessage', {
  intent: bcs.u8(),
  timestamp_ms: bcs.u64(),
  payload: Receipt,
})

const hexToBytes = (h: string) => Uint8Array.from(h.match(/.{2}/g)!.map((b) => parseInt(b, 16)))
const toHex = (b: Uint8Array) => Array.from(b).map((x) => x.toString(16).padStart(2, '0')).join('')

const doc = JSON.parse(
  readFileSync(new URL('../docs/receipt-vectors.json', import.meta.url), 'utf8'),
)

let failures = 0
for (const v of doc.vectors) {
  const f = v.fields
  const bytes = IntentMessage.serialize({
    intent: f.intent,
    timestamp_ms: BigInt(f.timestamp_ms),
    payload: {
      receipt_id: hexToBytes(f.receipt_id),
      config_hash: hexToBytes(f.config_hash),
      provider: f.provider,
      endpoint_host: f.endpoint_host,
      tls_cert_sha256: hexToBytes(f.tls_cert_sha256),
      request_blob: BigInt(f.request_blob),
      upstream_request_blob: BigInt(f.upstream_request_blob),
      upstream_headers_hash: hexToBytes(f.upstream_headers_hash),
      model_id: f.model_id,
      provider_request_id: f.provider_request_id,
      response_blob: BigInt(f.response_blob),
      provider_meta_hash: hexToBytes(f.provider_meta_hash),
      input_tokens: BigInt(f.input_tokens),
      cache_creation_tokens: BigInt(f.cache_creation_tokens),
      cache_read_tokens: BigInt(f.cache_read_tokens),
      output_tokens: BigInt(f.output_tokens),
      outcome: f.outcome,
    },
  }).toBytes()

  const got = toHex(bytes)
  if (bytes.length !== v.byte_length || got !== v.expected_bcs_hex) {
    failures++
    console.log(`FAIL ${v.name}: len ${bytes.length} (expected ${v.byte_length})`)
    console.log(`  got      ${got}`)
    console.log(`  expected ${v.expected_bcs_hex}`)
  } else {
    console.log(`PASS ${v.name}: ${bytes.length} bytes match`)
  }
}
console.log(failures === 0 ? 'ALL VECTORS VERIFIED' : `${failures} VECTOR(S) FAILED`)
process.exit(failures === 0 ? 0 : 1)
